name: CallCompose
on:
 push:
   branches: [main]   
 workflow_dispatch:
jobs:
  ci:
   runs-on: ubunutu-latest
   steps:
     - uses: actions/checkout@v3
     - id: foo
       uses: ./.github/Composite
       with:
          who-to-greet: 'Mona the Octocat'
     - run: echo random-number ${{ steps.foo.outputs.random-number }}
       shell: bash
